# Generated by Django 5.2.6 on 2025-09-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de fim do ciclo'),
        ),
    ]
