# Generated by Django 5.2.6 on 2025-11-27 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_dica_options_dica_categoria_dica_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrociclo',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrociclo',
            name='atividades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrociclo',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrociclo',
            name='sintomas',
            field=models.TextField(),
        ),
    ]
